name: ChallengePlugin
version: ${project.version}
main: de.floxyii.challengeplugin.ChallengePlugin
api-version: 1.18
authors: [ Floxyii ]
description: A challenge Plugin

commands:
  timer:
    description: Start the timer! (/timer <start> <stop> <reset> <remove>)
  challenge:
    description: Start the different challenges! (/challenge <start "challenge name"> <stop> <resume>)
  module:
    description: Add some small modules to your challenge!
  waypoint:
    description: Create waypoints!